import { SERVICES } from './site.config';

const descriptions: Record<string, string> = {
  'roof-repair': 'Call for shingle repairs, flashing fixes, roof leak tracing, storm-related damage checks, and practical repair options before water reaches ceilings, insulation, or decking.',
  'emergency-roof-repair': 'When a roof leak appears after wind or heavy rain, call for fast triage, temporary protection guidance, and a repair visit focused on stopping active water entry.',
  'roof-replacement': 'Get a straightforward roof replacement conversation: condition check, shingle options, ventilation review, decking concerns, timeline, and a clear estimate.',
  'storm-damage-roof-repair': 'After Kentucky storms, have wind, hail, flashing, ridge, valley, and gutter-related roof concerns reviewed without exaggerated damage claims.',
  'roof-inspection': 'A roof inspection helps you understand visible shingle wear, flashing risks, soft spots, vent details, gutter drainage, and whether repair or replacement is the next move.',
  'roof-leak-repair': 'Roof leaks often start at pipe boots, valleys, chimney flashing, wall transitions, or lifted shingles. The repair starts with finding the water path, not guessing.',
};

const bullets: Record<string, string[]> = {
  'roof-repair': ['Missing or lifted shingles', 'Pipe boot and roof vent leaks', 'Chimney and wall flashing repairs', 'Valley and ridge cap problems', 'Small storm-related repairs'],
  'emergency-roof-repair': ['Active leak triage', 'Wind-lifted shingle response', 'Temporary protection guidance', 'Storm damage review', 'Priority scheduling when water is entering'],
  'roof-replacement': ['Shingle replacement options', 'Decking and ventilation review', 'Tear-off planning', 'Cleanup expectations', 'Clear quote before work begins'],
  'storm-damage-roof-repair': ['Wind and hail indicators', 'Flashing and ridge checks', 'Gutter and drainage review', 'Conservative documentation', 'Repair-first recommendations when appropriate'],
  'roof-inspection': ['Roof age and wear review', 'Shingle, vent, and flashing checks', 'Attic and moisture clues', 'Repair priority list', 'Replacement timing guidance'],
  'roof-leak-repair': ['Leak source tracing', 'Pipe boot replacement', 'Valley and flashing fixes', 'Gutter-related water issues', 'Interior water-entry clues'],
};

const faqs: Record<string, { q: string; a: string }[]> = {
  'roof-repair': [
    { q: 'When should I call for roof repair?', a: 'Call when shingles are missing, water stains appear, flashing looks loose, granules collect in gutters, or a recent storm left roof debris. Small repairs are easier to handle before water reaches decking or insulation.' },
    { q: 'Can a roof be repaired instead of replaced?', a: 'Often yes. If the roof has localized damage and the surrounding shingles are still serviceable, repair can make sense. Replacement becomes more likely when wear is widespread or leaks keep returning.' },
  ],
  'emergency-roof-repair': [
    { q: 'What counts as a roofing emergency?', a: 'Active water entry, missing shingles after wind, damaged flashing during rain, or roof damage that exposes decking should be treated as urgent. Call first so the next step is safe and practical.' },
    { q: 'Should I climb on the roof during a leak?', a: 'No. Stay inside, move valuables, contain dripping water if safe, and call for roofing help. Wet shingles, ladders, and storm conditions are dangerous.' },
  ],
  'roof-replacement': [
    { q: 'How do I know if I need roof replacement?', a: 'Replacement may be the better option when shingles are brittle, curling, losing granules across large areas, leaking in multiple places, or nearing the end of their service life.' },
    { q: 'What affects roof replacement cost?', a: 'Roof size, slope, layers, decking condition, shingle choice, ventilation, flashing detail, and access all affect cost. A clear estimate should separate options and explain what is included.' },
  ],
  'storm-damage-roof-repair': [
    { q: 'Should I get a roof checked after a storm?', a: 'Yes if you see missing shingles, debris impact, gutter damage, ceiling stains, or neighbors reporting roof damage. A ground-level check can catch issues before the next rain.' },
    { q: 'Do you promise insurance approval?', a: 'No. Insurance decisions belong to the carrier. The roofing visit can document visible conditions and explain repair options without making guaranteed claim promises.' },
  ],
  'roof-inspection': [
    { q: 'What is checked during a roof inspection?', a: 'A practical inspection reviews shingles, flashing, vents, valleys, ridge caps, gutters, visible drainage patterns, and interior clues when relevant.' },
    { q: 'Can an inspection help before buying or selling?', a: 'Yes. A roof condition check can help clarify repair priorities before a transaction, but it should not replace any inspection required by a lender, buyer, or insurer.' },
  ],
  'roof-leak-repair': [
    { q: 'Why is my roof leaking if shingles look fine?', a: 'Leaks often come from flashing, pipe boots, valleys, wall transitions, nail pops, or gutter overflow. The visible drip inside is rarely directly below the roof entry point.' },
    { q: 'How fast should I call after seeing a stain?', a: 'Call as soon as you see staining, dripping, bubbling paint, or damp insulation. Waiting can turn a small roof detail problem into drywall, insulation, or decking damage.' },
  ],
};

const defaultSteps = [
  'Describe what you see from the ground or inside the home.',
  'Stay off wet, steep, or storm-damaged roof surfaces.',
  'Call for a roofing visit focused on the likely source and next step.',
];

const coreRelatedLinks = [
  { href: '/roof-repair', label: 'Roof Repair' },
  { href: '/roof-leak-repair', label: 'Roof Leak Repair' },
  { href: '/storm-damage-roof-repair', label: 'Storm Damage Roof Repair' },
  { href: '/roof-inspection', label: 'Roof Inspection' },
  { href: '/contact', label: 'Request Roofing Help' },
];

export const intentPages = [
  {
    slug: 'roof-leaking-after-storm-lexington-ky',
    title: 'Roof Leaking After Storm in Lexington, KY',
    short: 'Urgent help for ceiling drips, attic moisture, lifted shingles, and storm-related roof leaks.',
    image: '/images/roofing/intent/roof-leaking-after-storm-lexington-ky.png',
    alt: 'Roofer checking a Lexington home after a storm leak',
    eyebrow: 'High-intent storm leak help',
    description: 'If water starts dripping after heavy rain or wind, the fastest move is to protect the inside, avoid the roof, and call for roof leak tracing in Lexington.',
    bullets: ['New dripping after heavy rain', 'Ceiling stains or bubbling paint', 'Lifted shingles near valleys or edges', 'Pipe boot, vent, or flashing leaks', 'Storm debris near gutters or roof edges'],
    faqs: [
      { q: 'What should I do first if the roof leaks after a storm?', a: 'Move valuables, contain dripping water if it is safe, take photos of visible interior damage, and call for roofing help. Do not climb onto a wet or storm-damaged roof.' },
      { q: 'Can a storm leak be repaired the same day?', a: 'Some small leaks can be stabilized quickly, while hidden flashing or decking issues may need a scheduled repair. The first call should focus on stopping active water entry and identifying the likely source.' },
      { q: 'Where do storm roof leaks usually start?', a: 'Common sources include lifted shingles, valleys, pipe boots, chimney flashing, ridge details, wall transitions, and clogged gutters forcing water backward.' },
    ],
    relatedLinks: [
      { href: '/emergency-roof-repair', label: 'Emergency Roof Repair' },
      { href: '/roof-leak-repair', label: 'Roof Leak Repair' },
      { href: '/storm-damage-roof-repair', label: 'Storm Damage Roof Repair' },
      { href: '/water-stains-on-ceiling-lexington-ky', label: 'Water Stains on Ceiling' },
      { href: '/contact', label: 'Call About a Roof Leak' },
    ],
    steps: defaultSteps,
    schemaServiceType: 'Storm roof leak repair',
  },
  {
    slug: 'missing-shingles-lexington-ky',
    title: 'Missing Shingles in Lexington, KY',
    short: 'Repair wind-lifted, cracked, missing, or loose shingles before rain reaches the roof deck.',
    image: '/images/roofing/intent/missing-shingles-lexington-ky.png',
    alt: 'Roofer inspecting missing shingles on a Lexington roof',
    eyebrow: 'Wind damage roof repair',
    description: 'Missing shingles can expose underlayment and fasteners to water. Call for a focused shingle repair review before the next heavy Kentucky rain.',
    bullets: ['Single or grouped missing shingles', 'Shingles found in the yard', 'Creased or wind-lifted tabs', 'Exposed nail lines or underlayment', 'Granules collecting near downspouts'],
    faqs: [
      { q: 'Is one missing shingle urgent?', a: 'Yes, it can be. One missing shingle may expose fasteners or underlayment. It is easier to check and repair before wind opens a larger section.' },
      { q: 'Can missing shingles cause a leak right away?', a: 'They can, especially during wind-driven rain or if the missing area is near a valley, ridge, wall, or vent detail.' },
      { q: 'Should I save shingles that blew off?', a: 'If it is safe, saving a loose shingle can help identify color and material style, but do not walk the roof to retrieve it.' },
    ],
    relatedLinks: [
      { href: '/roof-repair', label: 'Roof Repair' },
      { href: '/storm-damage-roof-repair', label: 'Storm Damage Roof Repair' },
      { href: '/roof-inspection', label: 'Roof Inspection' },
      { href: '/same-day-roof-repair-lexington-ky', label: 'Same-Day Roof Repair' },
      { href: '/contact', label: 'Request Shingle Repair' },
    ],
    steps: defaultSteps,
    schemaServiceType: 'Missing shingle repair',
  },
  {
    slug: 'hail-damaged-roof-lexington-ky',
    title: 'Hail Damaged Roof in Lexington, KY',
    short: 'Check shingle bruising, granule loss, vents, gutters, and storm indicators after hail.',
    image: '/images/roofing/intent/hail-damaged-roof-lexington-ky.png',
    alt: 'Roofing inspection for possible hail damage in Lexington',
    eyebrow: 'Hail damage roof inspection',
    description: 'After hail, visible damage can be subtle. A roof check can separate normal wear from possible storm impact without exaggerating what is visible.',
    bullets: ['Granule loss near downspouts', 'Dented soft metal vents or gutters', 'Bruised asphalt shingles', 'Damaged ridge caps', 'Interior stains after hail and rain'],
    faqs: [
      { q: 'How do I know if hail damaged my roof?', a: 'Look from the ground for dented gutters, loose granules near downspouts, missing shingles, or new leaks. A roof inspection can review shingle and metal details more closely.' },
      { q: 'Do hail marks always mean replacement?', a: 'No. The next step depends on roof age, damage pattern, shingle condition, and whether water-entry risk is present. Some roofs need repair, others need broader evaluation.' },
      { q: 'Can you help with documentation?', a: 'A roofing visit can document visible roof conditions with photos and notes, but it should not promise insurance approval or claim outcomes.' },
    ],
    relatedLinks: [
      { href: '/storm-damage-roof-repair', label: 'Storm Damage Roof Repair' },
      { href: '/roof-inspection', label: 'Roof Inspection' },
      { href: '/roof-insurance-claim-help-lexington-ky', label: 'Roof Insurance Claim Help' },
      { href: '/roof-replacement', label: 'Roof Replacement' },
      { href: '/contact', label: 'Schedule Hail Roof Check' },
    ],
    steps: defaultSteps,
    schemaServiceType: 'Hail damage roof inspection',
  },
  {
    slug: 'roof-insurance-claim-help-lexington-ky',
    title: 'Roof Insurance Claim Help in Lexington, KY',
    short: 'Conservative roof documentation, repair scope discussion, and storm damage photos when needed.',
    image: '/images/roofing/intent/roof-insurance-claim-help-lexington-ky.png',
    alt: 'Roofing paperwork and shingle sample for a Lexington roof claim discussion',
    eyebrow: 'Storm documentation support',
    description: 'If storm damage may involve insurance, call for roofing documentation and repair guidance. Insurance approval decisions stay with the carrier.',
    bullets: ['Visible roof condition photos', 'Repair scope conversation', 'Storm-related damage notes', 'Shingle, flashing, vent, and gutter review', 'No promise of claim approval'],
    faqs: [
      { q: 'Can a roofer approve my insurance claim?', a: 'No. Only the insurance carrier makes claim decisions. A roofing visit can document visible conditions and explain repair or replacement needs.' },
      { q: 'Should I call a roofer before or after insurance?', a: 'If the roof is leaking or visibly damaged, call for safety and repair guidance first. You can then decide what documentation may be useful for your carrier.' },
      { q: 'What should I keep after a storm?', a: 'Keep photos of interior leaks, exterior debris, missing shingles visible from the ground, and any dates when damage was noticed.' },
    ],
    relatedLinks: [
      { href: '/storm-damage-roof-repair', label: 'Storm Damage Roof Repair' },
      { href: '/hail-damaged-roof-lexington-ky', label: 'Hail Damaged Roof' },
      { href: '/roof-inspection', label: 'Roof Inspection' },
      { href: '/roof-replacement', label: 'Roof Replacement' },
      { href: '/contact', label: 'Discuss Roof Documentation' },
    ],
    steps: defaultSteps,
    schemaServiceType: 'Roof insurance documentation support',
  },
  {
    slug: 'emergency-roof-tarping-lexington-ky',
    title: 'Emergency Roof Tarping in Lexington, KY',
    short: 'Temporary roof protection guidance when water is entering and a full repair needs scheduling.',
    image: '/images/roofing/intent/emergency-roof-tarping-lexington-ky.png',
    alt: 'Roofers placing a tarp on a Lexington home after rain',
    eyebrow: 'Temporary storm protection',
    description: 'Emergency tarping can reduce water entry when a roof opening, missing shingles, or storm damage cannot be permanently repaired immediately.',
    bullets: ['Active leak after wind or rain', 'Missing shingles over living space', 'Tree limb or debris impact', 'Temporary protection before repair', 'Safety-first storm response'],
    faqs: [
      { q: 'When does a roof need emergency tarping?', a: 'Tarping may help when water is entering, shingles are missing over a vulnerable area, or storm damage exposes roof materials before a permanent repair can be made.' },
      { q: 'Is a tarp a permanent roof repair?', a: 'No. Tarping is temporary protection. The roof still needs repair or replacement guidance after conditions are safe.' },
      { q: 'Should I tarp the roof myself?', a: 'Usually no. Wet roofs, ladders, and storm conditions are dangerous. Call first and avoid climbing onto the roof.' },
    ],
    relatedLinks: [
      { href: '/emergency-roof-repair', label: 'Emergency Roof Repair' },
      { href: '/roof-leaking-after-storm-lexington-ky', label: 'Roof Leaking After Storm' },
      { href: '/storm-damage-roof-repair', label: 'Storm Damage Roof Repair' },
      { href: '/same-day-roof-repair-lexington-ky', label: 'Same-Day Roof Repair' },
      { href: '/contact', label: 'Call for Tarping Help' },
    ],
    steps: defaultSteps,
    schemaServiceType: 'Emergency roof tarping',
  },
  {
    slug: 'water-stains-on-ceiling-lexington-ky',
    title: 'Water Stains on Ceiling in Lexington, KY',
    short: 'Trace ceiling stains to possible roof leaks, flashing problems, attic moisture, or storm damage.',
    image: '/images/roofing/intent/water-stains-on-ceiling-lexington-ky.png',
    alt: 'Homeowner noticing a ceiling water stain in Lexington',
    eyebrow: 'Interior leak warning signs',
    description: 'A ceiling stain can mean the roof leak started before the drip appeared. Call for roof leak tracing before moisture spreads through drywall or insulation.',
    bullets: ['Brown or yellow ceiling stains', 'Bubbling paint or damp drywall', 'Attic moisture after rain', 'Stains near chimneys or vents', 'Recurring stains after storms'],
    faqs: [
      { q: 'Does a ceiling stain always mean a roof leak?', a: 'Not always. Plumbing, condensation, and HVAC issues can also stain ceilings. A roof-focused check looks for roof paths such as flashing, valleys, vents, and shingles.' },
      { q: 'How urgent is a ceiling water stain?', a: 'Treat it as time-sensitive, especially after rain. The visible stain may appear after moisture has already moved through insulation or drywall.' },
      { q: 'What should I check before calling?', a: 'Note when the stain appears, whether it follows rain, and whether the attic smells damp. Do not cut drywall or climb onto the roof just to investigate.' },
    ],
    relatedLinks: [
      { href: '/roof-leak-repair', label: 'Roof Leak Repair' },
      { href: '/roof-leaking-after-storm-lexington-ky', label: 'Roof Leaking After Storm' },
      { href: '/roof-inspection', label: 'Roof Inspection' },
      { href: '/emergency-roof-repair', label: 'Emergency Roof Repair' },
      { href: '/contact', label: 'Call About Ceiling Stains' },
    ],
    steps: defaultSteps,
    schemaServiceType: 'Ceiling stain roof leak inspection',
  },
  {
    slug: 'same-day-roof-repair-lexington-ky',
    title: 'Same-Day Roof Repair in Lexington, KY',
    short: 'Fast roofing triage for leaks, missing shingles, flashing issues, and urgent repair priorities.',
    image: '/images/roofing/intent/same-day-roof-repair-lexington-ky.png',
    alt: 'Roofer preparing same-day roof repair materials in Lexington',
    eyebrow: 'Fast repair scheduling',
    description: 'When a roof issue cannot wait, call for same-day roofing triage in Lexington. Availability depends on weather, safety, and repair scope.',
    bullets: ['Active roof leak triage', 'Missing shingle repair review', 'Pipe boot or flashing concerns', 'Storm-related roof checks', 'Priority call routing for urgent issues'],
    faqs: [
      { q: 'Can every repair be done the same day?', a: 'No. Weather, roof pitch, material availability, and damage scope all matter. Same-day help starts with triage and may include temporary protection or scheduling the right repair.' },
      { q: 'What roof problems should not wait?', a: 'Active leaks, exposed decking, missing shingles before heavy rain, interior ceiling stains, and storm damage over living space should be handled quickly.' },
      { q: 'What should I say when I call?', a: 'Share the address area, what happened, when it started, whether water is entering, and whether the roof is steep or difficult to access.' },
    ],
    relatedLinks: [
      { href: '/emergency-roof-repair', label: 'Emergency Roof Repair' },
      { href: '/roof-repair', label: 'Roof Repair' },
      { href: '/emergency-roof-tarping-lexington-ky', label: 'Emergency Roof Tarping' },
      { href: '/missing-shingles-lexington-ky', label: 'Missing Shingles' },
      { href: '/contact', label: 'Call for Same-Day Help' },
    ],
    steps: defaultSteps,
    schemaServiceType: 'Same-day roof repair',
  },
  {
    slug: '24-hour-roofer-lexington-ky',
    title: '24-Hour Roofer in Lexington, KY',
    short: 'Phone-first roofing help for urgent leaks, storm damage, and roof safety questions.',
    image: '/images/roofing/intent/24-hour-roofer-lexington-ky.png',
    alt: 'Homeowner calling a roofer during a roof leak in Lexington',
    eyebrow: 'Urgent roofing phone help',
    description: 'If a roof issue happens outside normal hours, call the number on this site for urgent triage and the next available roofing response.',
    bullets: ['After-hours roof leak calls', 'Storm damage triage', 'Temporary protection guidance', 'Emergency repair scheduling', 'Safety-first next steps'],
    faqs: [
      { q: 'Can I call at night for a roof leak?', a: 'Yes. If water is entering, call and explain what is happening. The safest next step may be temporary protection, scheduling, or interior damage control until roof work is safe.' },
      { q: 'Will roofers work during active storms?', a: 'Roof work depends on safety. Wet roofs, lightning, high wind, and darkness can make exterior work unsafe. A call still helps establish the next step.' },
      { q: 'What should I do while waiting?', a: 'Move valuables, contain water if safe, take photos, and avoid ladders or wet roof surfaces.' },
    ],
    relatedLinks: [
      { href: '/emergency-roof-repair', label: 'Emergency Roof Repair' },
      { href: '/roof-leaking-after-storm-lexington-ky', label: 'Roof Leaking After Storm' },
      { href: '/emergency-roof-tarping-lexington-ky', label: 'Emergency Roof Tarping' },
      { href: '/water-stains-on-ceiling-lexington-ky', label: 'Water Stains on Ceiling' },
      { href: '/contact', label: 'Call Now' },
    ],
    steps: defaultSteps,
    schemaServiceType: '24-hour roofing help',
  },
  {
    slug: 'free-roof-inspection-lexington-ky',
    title: 'Free Roof Inspection in Lexington, KY',
    short: 'Request a roof condition conversation for shingles, leaks, storm concerns, and replacement timing.',
    image: '/images/roofing/intent/free-roof-inspection-lexington-ky.png',
    alt: 'Roof inspector reviewing shingles on a Lexington home',
    eyebrow: 'Roof condition check',
    description: 'A roof inspection helps identify visible roof concerns, prioritize repairs, and decide whether replacement should be discussed.',
    bullets: ['Shingle wear review', 'Flashing, vent, and valley checks', 'Leak source clues', 'Storm damage indicators', 'Repair versus replacement guidance'],
    faqs: [
      { q: 'What is included in a roof inspection?', a: 'A practical roof inspection reviews visible shingles, flashing, vents, valleys, gutters, and interior clues when relevant.' },
      { q: 'Is the inspection always free?', a: 'This page is built for free inspection intent, but availability and terms should be confirmed by phone before scheduling.' },
      { q: 'Will an inspection tell me if I need replacement?', a: 'It can help clarify whether damage is localized or widespread, but the final recommendation should be based on actual roof condition.' },
    ],
    relatedLinks: [
      { href: '/roof-inspection', label: 'Roof Inspection' },
      { href: '/roof-repair', label: 'Roof Repair' },
      { href: '/roof-replacement', label: 'Roof Replacement' },
      { href: '/hail-damaged-roof-lexington-ky', label: 'Hail Damaged Roof' },
      { href: '/contact', label: 'Request Inspection' },
    ],
    steps: defaultSteps,
    schemaServiceType: 'Roof inspection',
  },
  {
    slug: 'roof-financing-lexington-ky',
    title: 'Roof Financing in Lexington, KY',
    short: 'Talk through roof replacement timing, repair priorities, and payment-option questions before work begins.',
    image: '/images/roofing/intent/roof-financing-lexington-ky.png',
    alt: 'Homeowner reviewing roof replacement options in Lexington',
    eyebrow: 'Roof replacement planning',
    description: 'If replacement is needed but timing and budget matter, call to discuss roof scope, priorities, and available next steps without pressure.',
    bullets: ['Replacement scope discussion', 'Repair-now versus replace-soon planning', 'Material and ventilation options', 'Budget-priority conversation', 'Clear estimate before decisions'],
    faqs: [
      { q: 'Can roof replacement be planned around budget?', a: 'Yes. A roof conversation can separate urgent repairs from replacement planning and clarify what work should be prioritized first.' },
      { q: 'Should I finance a repair or replacement?', a: 'That depends on roof condition, urgency, budget, and available options. The roofing estimate should explain the scope clearly before any decision.' },
      { q: 'Can a repair buy time before replacement?', a: 'Sometimes. Localized repairs can help when the surrounding roof is serviceable. Widespread wear or repeated leaks may make replacement more practical.' },
    ],
    relatedLinks: [
      { href: '/roof-replacement', label: 'Roof Replacement' },
      { href: '/roof-inspection', label: 'Roof Inspection' },
      { href: '/roof-repair', label: 'Roof Repair' },
      { href: '/free-roof-inspection-lexington-ky', label: 'Free Roof Inspection' },
      { href: '/contact', label: 'Discuss Roof Options' },
    ],
    steps: defaultSteps,
    schemaServiceType: 'Roof replacement planning',
  },
];

export const areaDetails = [
  { slug: 'lexington', title: 'Roofing Contractors in Lexington, KY', intro: 'Lexington homes deal with humid summers, spring storms, wind-driven rain, and aging shingle roofs. Call for roof repair, inspections, storm damage review, leak tracing, or replacement guidance.', neighborhoods: ['Chevy Chase', 'Hamburg', 'Beaumont', 'Masterson Station', 'Tates Creek'] },
  { slug: 'nicholasville', title: 'Roofing Contractors in Nicholasville, KY', intro: 'Nicholasville homeowners call for leak repairs, storm checks, shingle replacement options, and roof inspections across Jessamine County neighborhoods.', neighborhoods: ['Brannon Crossing', 'Downtown Nicholasville', 'Keene', 'Wilmore Road', 'Southbrook'] },
  { slug: 'georgetown', title: 'Roofing Contractors in Georgetown, KY', intro: 'Georgetown roofs can take wind, hail, and drainage wear. Get practical help for storm damage, roof leaks, inspections, and replacement planning.', neighborhoods: ['Cherry Blossom', 'Downtown Georgetown', 'Paynes Depot', 'Elkhorn Green', 'Oxford'] },
  { slug: 'richmond', title: 'Roofing Contractors in Richmond, KY', intro: 'Richmond homeowners can call for roof leak repair, missing shingles, storm damage checks, and replacement estimates throughout Madison County.', neighborhoods: ['Downtown Richmond', 'Boonesborough', 'Berea Road', 'Lake Reba', 'Eastern Bypass'] },
  { slug: 'versailles', title: 'Roofing Contractors in Versailles, KY', intro: 'Versailles homes need careful shingle, flashing, and gutter checks after wind or heavy rain. Call for roof repairs, inspections, and replacement options.', neighborhoods: ['Downtown Versailles', 'Amsden', 'Mortonsville', 'Midway Road', 'Pisgah Pike'] },
  { slug: 'winchester', title: 'Roofing Contractors in Winchester, KY', intro: 'Winchester homeowners can request help with roof leaks, shingle wear, storm damage review, and roof replacement planning in Clark County.', neighborhoods: ['Downtown Winchester', 'Colby Hills', 'Boonesboro Road', 'Strode Station', 'Indian Old Fields'] },
];

export const serviceDetails = [
  ...SERVICES.map(service => ({
    ...service,
    eyebrow: service.slug === 'emergency-roof-repair' ? 'Lexington emergency roofing help' : 'Lexington roofing service',
    title: `${service.title} in Lexington, KY`,
    description: descriptions[service.slug],
    bullets: bullets[service.slug],
    faqs: faqs[service.slug],
    relatedLinks: coreRelatedLinks.filter(link => link.href !== `/${service.slug}`),
    steps: defaultSteps,
    schemaServiceType: service.title,
  })),
  ...intentPages,
];
